FROM ubuntu:16.04

WORKDIR /amp

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    git \
    libssl-dev \
    openssl \
    python \
    python3 \
    pkg-config \
    cmake \
    libxcb1-dev \
    curl

RUN curl https://sh.rustup.rs -sSf > rustup
RUN chmod +x rustup && ./rustup -y
RUN ~/.cargo/bin/cargo install amp
